spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888

logging.level:
  org.hibernate.SQL: debug


keycloak:
  enabled: true
  realm: choi
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: boot
  credentials:
    secret: aiV1caApbRA9aZn0ujLWm1Fo2F976A63
  use-resource-role-mappings: true
  bearer-only: true